management:
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  main:
    banner-mode: "off"
  kafka:
    consumer:
      group-id: foo
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: org.nowpat.dto,org.apache.commons.lang3.tuple
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  data:
    rest:
      base-path: /consumer

server:
  port: 8082
  context-path: /consumer

paths:
  base: /consumer
  collect: /collect
  allnbprates: /allnbprates