management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    shutdown:
      enabled: true
    health:
      enabled: true
    web:
      exposure:
        include: "*"

#kafka:
#  host: localhost
#  port: 9092
#
spring:
  main:
    banner-mode: "off"
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  jackson:
    serialization:
      write_dates_as_timestamps: false

server:
  port: 8080

nbpapi:
  protocol: http
  host: api.nbp.pl
  path: /api/exchangerates/tables/{p1}/{p2}/{p3}

