spring:
  main:
    banner-mode: "off"
  kafka:
    client-id: "test_processor"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: foo
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: org.nowpat.dto
  jackson:
    serialization:
      write_dates_as_timestamps: false

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    shutdown:
      enabled: true
    health:
      enabled: true
    web:
      exposure:
        include: "*"

server:
  port: 8081
  servlet:
    context-path: /apibase

topics:
  input: test_topic
  ttd: test_topic_ttd
  ttsd: test_topic_ttsd
  nbp: test_topic_nbprates
  output: test_topic_processed
